swagger: "2.0"
info:
  title: Servicio de Gestión de Productos - AgroWeb
  description: API REST para registrar y consultar productos del agro colombiano.
  version: "1.0.1"
host: "localhost:5000"
basePath: "/"
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /products:
    post:
      summary: Registrar un producto
      description: Crea un nuevo producto del agro colombiano.
      parameters:
        - in: body
          name: body
          description: Datos del producto a registrar
          required: true
          schema:
            $ref: "#/definitions/ProductInput"
      responses:
        201:
          description: Producto creado exitosamente
          schema:
            $ref: "#/definitions/Product"
          examples:
            application/json:
              productId: "P001"
              name: "Papa Pastusa"
              description: "Papa de excelente calidad"
              category: "Tubérculo"
              price: 1200.0
              stock: 100
              unit: "kg"
              origin: "Boyacá"
              imageUrl: "https://example.com/images/papa.jpg"
              createdAt: "2025-06-16"
              updatedAt: "2025-06-16"
              isActive: true
        400:
          description: Error de validación o datos incompletos
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Faltan campos obligatorios: name, price"
        415:
          description: Content-Type no soportado
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Content-Type must be application/json"
        500:
          description: Error interno del servidor
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Error interno del servidor"
      x-curl-example:
        command: |
          curl -X POST http://localhost:5000/products -H "Content-Type: application/json" -d "{\"productId\": \"P001\", \"name\": \"Papa Pastusa\", \"description\": \"Papa de excelente calidad\", \"category\": \"Tubérculo\", \"price\": 1200.0, \"stock\": 100, \"unit\": \"kg\", \"origin\": \"Boyacá\", \"imageUrl\": \"https://example.com/images/papa.jpg\"}"
    get:
      summary: Listar todos los productos
      description: Devuelve una lista de todos los productos registrados.
      responses:
        200:
          description: Lista de productos
          schema:
            type: array
            items:
              $ref: "#/definitions/Product"
          examples:
            application/json:
              - productId: "P001"
                name: "Papa Pastusa"
                description: "Papa de excelente calidad"
                category: "Tubérculo"
                price: 1200.0
                stock: 100
                unit: "kg"
                origin: "Boyacá"
                imageUrl: "https://example.com/images/papa.jpg"
                createdAt: "2025-06-16"
                updatedAt: "2025-06-16"
                isActive: true
              - productId: "P002"
                name: "Mango Tommy"
                description: "Mango dulce y jugoso"
                category: "Fruta"
                price: 2500.0
                stock: 50
                unit: "kg"
                origin: "Tolima"
                imageUrl: "https://example.com/images/mango.jpg"
                createdAt: "2025-06-16"
                updatedAt: "2025-06-16"
                isActive: true
        500:
          description: Error interno del servidor
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Error interno del servidor"
      x-curl-example:
        command: |
          curl -X GET http://localhost:5000/products

  /products/{productId}:
    get:
      summary: Consultar producto por ID
      description: Devuelve los datos de un producto específico según su ID.
      parameters:
        - name: productId
          in: path
          required: true
          type: string
          description: ID del producto a consultar
      responses:
        200:
          description: Producto encontrado
          schema:
            $ref: "#/definitions/Product"
          examples:
            application/json:
              productId: "P001"
              name: "Papa Pastusa"
              description: "Papa de excelente calidad"
              category: "Tubérculo"
              price: 1200.0
              stock: 100
              unit: "kg"
              origin: "Boyacá"
              imageUrl: "https://example.com/images/papa.jpg"
              createdAt: "2025-06-16"
              updatedAt: "2025-06-16"
              isActive: true
        400:
          description: ID inválido
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "ID inválido"
        404:
          description: Producto no encontrado
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Producto no encontrado"
        500:
          description: Error interno del servidor
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Error interno del servidor"
      x-curl-example:
        command: |
          curl -X GET http://localhost:5000/products/P001

  /test:
    get:
      summary: Ruta de prueba
      description: Verifica que el servicio está activo.
      responses:
        200:
          description: El servicio está activo
          schema:
            type: string
          examples:
            application/json: "Test route is working!"
        500:
          description: Error interno del servidor
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Error interno del servidor"

definitions:
  ProductInput:
    type: object
    required:
      - productId
      - name
      - description
      - category
      - price
      - stock
      - unit
      - origin
      - imageUrl
    properties:
      productId:
        type: string
        example: P001
      name:
        type: string
        example: Papa Pastusa
      description:
        type: string
        example: Papa de excelente calidad
      category:
        type: string
        example: Tubérculo
      price:
        type: number
        example: 1200.0
      stock:
        type: integer
        example: 100
      unit:
        type: string
        example: kg
      origin:
        type: string
        example: Boyacá
      imageUrl:
        type: string
        example: https://example.com/images/papa.jpg

  Product:
    allOf:
      - $ref: "#/definitions/ProductInput"
      - type: object
        properties:
          createdAt:
            type: string
            format: date
            example: 2025-06-16
          updatedAt:
            type: string
            format: date
            example: 2025-06-16
          isActive:
            type: boolean
            example: true

  Error:
    type: object
    properties:
      error:
        type: string
        example: "Producto no encontrado"